apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: httpd-app
  annotations: {}
spec:
  selector:
    matchLabels:
      app: httpd-app
  replicas: 3
  template:
    metadata:
      labels:
        app: httpd-app
    spec:
      volumes:
      - name: httpd-volume
        persistentVolumeClaim:
          claimName: httpd-pvc
      containers:
        - name: container
          image: default-route-openshift-image-registry.apps.ext2.mtp.local/demo/httpd-24:2025-02-27-15-06-22
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
          - name: httpd-volume
            mountPath: /var/www/html/
          env:
            - name: HTTPD_SSL
              value: "off"
          args:
            - "/bin/sh"
            - "-c"
            - "rm -f /etc/httpd/conf.d/ssl.conf && httpd -DFOREGROUND"
      imagePullSecrets:
      - name: image-pull-secret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false
