kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: httpd-route
  namespace: demo
  labels:
    type: sharded
spec:
  to:
    kind: Service
    name: httpd-service
  tls: null
  host: cys.apache.com
  path: /
  port:
    targetPort: 8080
